#!/bin/bash -l
#SBATCH -q regular
#SBATCH -N 1
#SBATCH -c 32
#SBATCH -C haswell
#SBATCH -t 00:30:00
cd $SLURM_SUBMIT_DIR   # optional, since this is the default behavior
module load matlab
srun -n 1 -c 32 matlab -nodisplay -r toSubmit -logfile toSubmit.log
